movieapp/urls.py
from django.urls import path

from movieapp import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','img','year']

movieapp/views.py
from django.http import HttpResponse, request
from django.shortcuts import render, redirect
from . models import Movie
from  . forms import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">

        <form action="" method="POST" enctype="multipart/form-data">
             <h2><b>Add Form</b></h2>
            {% csrf_token %}
            <div>
                <div>
                    <span>Movie Name:</span>
                    <input type="text" name="name" placeholder="Enter your Movie Name" required><br><br>
                </div>
                <div>
                    <span>Movie Description:</span>
                    <textarea name="desc" placeholder="Enter Your Movie Description" required></textarea><br><br>
                </div>
                <div>
                    <span>Movie Year:</span>
                    <input type="text" name="year" placeholder="Enter Your Movie Year" required><br><br>
                </div>
                <div>
                    <span>Upload Image:</span>
                    <input type="file" name="img" required><br><br>
                </div>
            </div>
            <div class="button">
                <input type="submit" value="Submit">
            </div>
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'edit.css' %}">
<style>
    .add-button {
        background-color: #007BFF;
        color: #fff;
        padding-top: 5px;
        padding-left: 15px;
        padding-right: 15px;
        padding-bottom: 5px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 18px;
    }
</style>

</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
  Online Movie Store
  </a>
&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'movieapp:add_movie' %}" class="add-button">Add Movie</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  Are You Want to Delete this Movie?
  <input type="submit" value="OK">
</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<style>
    .movie-description {
        max-width: 500px;
        margin: 0 auto;
    }
</style>

<div style="text-align: center;">
    <br>
    <h2>{{ movie.name }}
    </h2>
    <img src="{{ movie.img.url }}" width="150" height="150"><br>
    <div class="movie-description">{{ movie.desc }}</div>
    <b> Year:</b>{{ movie.year }}<br>
     <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
     <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>

</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                    <h2>Update Form</h2>

            <label for="{{ form.name.id_for_label }}">Name:</label>
            {{ form.name }}
            <br>

            <label for="{{ form.desc.id_for_label }}">Description:</label>
            {{ form.desc }}
            <br>


            <label for="{{ form.year.id_for_label }}">Year:</label>
            {{ form.year }}
            <br>

            <label for="{{ form.img.id_for_label }}">Image:</label>
            {{ form.img }}


            <br>
            <input type="submit" value="Update">
        </form>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<style>
    .movies-container {
        text-align: left;
    }

    .movie-item {
        display: inline-block;
        margin: 10px;
        max-width: 200px;
    }

    .movie-name {
        color: green;
        display: block;
        font-size: 18px;
        margin-top: 5px;
        text-decoration: none;
    }

    .movie-image {
        width: 200px;
        height: 200px;
        object-fit: cover;
    }


</style>

<h2><b>Movies List:</b></h2>
<br><br>

<div class="movies-container">
    {% for movie in movie_list %}
    <div class="card movie-item">
        <img src="{{ movie.img.url }}" class="card-img-top movie-image" alt="{{ movie.name }}">
        <div class="card-body">
            <h5>{{ movie.name }}</h5><br>

             <a class="btn btn-warning" href="{% url 'movieapp:detail' movie.id %}">View Details</a>
<!--     <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>-->
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}